import { css } from '@emotion/react';

export const editorStyles = {
  root: css({
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    padding: '10px',
    borderRadius: 'var(--radii-md)',
    border: 'var(--border-accent)',
    background: 'var(--color-paper)',
    color: 'var(--color-ink)',
    boxShadow:
      '0 20px 40px var(--editor-shadow), 0 0 0 4px var(--color-accent-light)',
    backdropFilter: 'blur(12px)',
  }),
  metaRow: css({
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  }),
  allDayLabel: css({
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 12,
    cursor: 'pointer',
    userSelect: 'none',
    color: 'var(--color-ink-muted)',
    flexShrink: 0,
  }),
  allDayCheckbox: css({
    width: 14,
    height: 14,
    cursor: 'pointer',
    accentColor: 'var(--color-accent)',
  }),
  timeInput: css({
    width: 84,
    height: 28,
    padding: '0 8px',
    fontSize: 12,
    fontFamily: 'var(--font-mono)',
    border: 'var(--border-default)',
    borderRadius: '999px',
    background: 'var(--color-paper-dark)',
    color: 'var(--color-ink)',
    outline: 'none',
    ':focus': {
      borderColor: 'var(--color-accent)',
    },
  }),
  dayBadge: css({
    height: 28,
    display: 'inline-flex',
    alignItems: 'center',
    padding: '0 10px',
    borderRadius: '999px',
    border: 'var(--border-default)',
    background: 'var(--color-paper-dark)',
    fontSize: 11,
    fontFamily: 'var(--font-mono)',
    color: 'var(--color-ink)',
  }),
  viewActions: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
  }),
  viewButton: css({
    height: 22,
    paddingInline: 8,
    borderRadius: 'var(--radii-sm)',
    border: 'var(--border-default)',
    background: 'var(--color-paper-dark)',
    color: 'var(--color-ink)',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 11,
    fontWeight: 600,
    cursor: 'pointer',
  }),
  viewDeleteButton: css({
    color: 'var(--color-danger)',
  }),
};
