import { css } from '@emotion/react';

export const mobileViewStyles = {
  root: css({
    flex: '1 1 auto',
    width: '100%',
    maxWidth: '100%',
    minWidth: 0,
    minHeight: 0,
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    padding: 12,
    background: 'var(--color-paper-light)',
    overflow: 'hidden',
  }),
  monthCard: css({
    display: 'grid',
    gap: 10,
    minWidth: 0,
    flexShrink: 0,
    padding: 12,
    borderRadius: 'var(--radii-lg)',
    border: 'var(--border-default)',
    background: 'var(--color-paper)',
  }),
  weekdays: css({
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    gap: 6,
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    color: 'var(--color-ink-muted)',
    fontFamily: 'var(--font-mono)',
  }),
  weekdayCell: css({
    textAlign: 'center',
  }),
  monthGrid: css({
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    gap: 6,
  }),
  dayButton: css({
    position: 'relative',
    aspectRatio: '1 / 1',
    borderRadius: 14,
    border: 'var(--border-default)',
    background: 'var(--day-bg)',
    color: 'var(--day-color)',
    cursor: 'pointer',
    display: 'grid',
    placeItems: 'center',
    fontSize: 13,
    fontWeight: 600,
    transition: 'transform 120ms ease, border-color 120ms ease',
    ':active': {
      transform: 'scale(0.98)',
    },
  }),
  dayButtonTaskCount: css({
    position: 'absolute',
    top: 6,
    right: 6,
    minWidth: 18,
    height: 18,
    padding: '0 5px',
    borderRadius: 999,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'var(--task-count-bg)',
    color: 'var(--task-count-color)',
    fontSize: 10,
    fontWeight: 700,
    lineHeight: 1,
  }),
  dayButtonHolidayMark: css({
    position: 'absolute',
    left: 8,
    right: 8,
    bottom: 6,
    height: 4,
    borderRadius: 999,
    background: 'var(--holiday-mark)',
  }),
  dayButtonHoliday: css({
    borderColor: 'var(--holiday-border)',
  }),
  dayButtonSelected: css({
    borderColor: 'var(--color-accent)',
    boxShadow: '0 0 0 3px var(--color-accent-light)',
  }),
  dayButtonToday: css({
    background: 'var(--color-accent)',
    color: '#ffffff',
  }),
  panel: css({
    position: 'relative',
    flex: '1 1 auto',
    minWidth: 0,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    padding: 12,
    borderRadius: 'var(--radii-lg)',
    border: 'var(--border-default)',
    background: 'var(--color-paper)',
    overflow: 'hidden',
  }),
  panelHeader: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    flexShrink: 0,
  }),
  panelTitle: css({
    display: 'grid',
    gap: 2,
    minWidth: 0,
  }),
  panelDate: css({
    fontFamily: 'var(--font-display)',
    fontSize: 20,
    fontWeight: 700,
    color: 'var(--color-ink)',
  }),
  panelMeta: css({
    fontSize: 11,
    color: 'var(--color-ink-muted)',
    fontFamily: 'var(--font-mono)',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  }),
  addButton: css({
    height: 34,
    padding: '0 12px',
    borderRadius: '999px',
    border: 'none',
    background: 'var(--color-accent)',
    color: '#ffffff',
    fontSize: 12,
    fontWeight: 700,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    cursor: 'pointer',
    flexShrink: 0,
  }),
  holidayList: css({
    display: 'grid',
    gap: 6,
    flexShrink: 0,
  }),
  tasksArea: css({
    flex: '1 1 auto',
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  }),
  emptyState: css({
    margin: 'auto 0',
    padding: '16px 12px',
    borderRadius: 16,
    background: 'var(--color-paper-dark)',
    color: 'var(--color-ink-muted)',
    fontSize: 12,
    textAlign: 'center',
  }),
  editorOverlay: css({
    position: 'absolute',
    insetInline: 12,
    top: 66,
    zIndex: 12,
    maxHeight: 'calc(100% - 78px)',
    overflow: 'auto',
  }),
};
